name: Backend Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ env.DOCKER_USERNAME }}/your-backend-image:latest .
          docker push ${{ env.DOCKER_USERNAME }}/your-backend-image:latest

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "${{ secrets.AWS_REGION }}"

      - name: Install SSH Client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@13.48.147.239 << 'EOF'
            docker pull ${{ env.DOCKER_USERNAME }}/your-backend-image:latest
            docker stop your-backend-container || true
            docker rm your-backend-container || true
            docker run -d -p 3000:3000 --name your-backend-container ${{ env.DOCKER_USERNAME }}/your-backend-image:latest
          EOF
