name: Frontend S3 Deploy

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build frontend
        run: |
          npm install  # Replace with your frontend build commands
          npm run build  # Replace with your frontend build commands

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude '.git/*' --delete
        env:
          AWS_S3_BUCKET: bekiraws
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
